/**
 * PR body builder — r2-10 auto-PR feature.
 *
 * Pure function: no I/O, no DB access, no side effects beyond the timestamp
 * generated at call time.  All external data (commits, handoff note) is
 * passed in so callers can inject stubs in tests.
 */

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface PrBodyInput {
  workflowName: string;
  recentCommits: string[];
  lastHandoffNote: string | null;
}

// ---------------------------------------------------------------------------
// buildPrBody
// ---------------------------------------------------------------------------

/**
 * Build the markdown body for an auto-generated GitHub PR.
 *
 * Format:
 *   Auto-generated by yoke on <ISO timestamp>
 *
 *   - <commit subject 1>
 *   - <commit subject 2>
 *   ...
 *
 *   ## Recent handoff note       ← only when lastHandoffNote is non-null
 *
 *   <lastHandoffNote text>
 *
 * @param workflowName  Name of the completed workflow (held in input for
 *                      callers that may extend the body in the future).
 * @param recentCommits Up to 10 commit subjects from the worktree.
 * @param lastHandoffNote  Note text from the last non-harness-injected
 *                         handoff entry, or null if none.
 */
export function buildPrBody({ workflowName: _wn, recentCommits, lastHandoffNote }: PrBodyInput): string {
  const ts = new Date().toISOString();
  const parts: string[] = [`Auto-generated by yoke on ${ts}`];

  if (recentCommits.length > 0) {
    parts.push('');
    parts.push(recentCommits.map((s) => `- ${s}`).join('\n'));
  }

  if (lastHandoffNote) {
    parts.push('');
    parts.push('## Recent handoff note');
    parts.push('');
    parts.push(lastHandoffNote);
  }

  return parts.join('\n');
}
