/**
 * Unit tests for buildPrBody — the pure PR body builder (r2-10).
 *
 * RC: The function is pure; takes {workflowName, recentCommits, lastHandoffNote}
 * and returns a string.  These tests assert structural properties without
 * depending on the exact ISO timestamp generated at call time.
 */

import { describe, it, expect } from 'vitest';
import { buildPrBody } from '../../src/server/github/pr-body.js';
import type { PrBodyInput } from '../../src/server/github/pr-body.js';

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function body(overrides: Partial<PrBodyInput> = {}): string {
  return buildPrBody({
    workflowName: 'my-workflow',
    recentCommits: [],
    lastHandoffNote: null,
    ...overrides,
  });
}

// ---------------------------------------------------------------------------
// Header
// ---------------------------------------------------------------------------

describe('buildPrBody — header', () => {
  it('starts with "Auto-generated by yoke on " followed by an ISO timestamp', () => {
    const result = body();
    expect(result).toMatch(/^Auto-generated by yoke on \d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d+Z/);
  });

  it('does not include the workflow name in the body text', () => {
    const result = body({ workflowName: 'unique-name-xyz' });
    expect(result).not.toContain('unique-name-xyz');
  });
});

// ---------------------------------------------------------------------------
// Commit list
// ---------------------------------------------------------------------------

describe('buildPrBody — commit subjects', () => {
  it('renders each commit as a "- " list item', () => {
    const result = body({ recentCommits: ['first commit', 'second commit'] });
    expect(result).toContain('- first commit');
    expect(result).toContain('- second commit');
  });

  it('renders all 10 commits when given 10', () => {
    const commits = Array.from({ length: 10 }, (_, i) => `commit ${i + 1}`);
    const result = body({ recentCommits: commits });
    for (const c of commits) {
      expect(result).toContain(`- ${c}`);
    }
  });

  it('renders no commit list when commits array is empty', () => {
    const result = body({ recentCommits: [] });
    expect(result).not.toContain('- ');
  });

  it('separates the header from commits with a blank line', () => {
    const result = body({ recentCommits: ['foo'] });
    // The blank line between header and commit list
    expect(result).toContain('\n\n- foo');
  });
});

// ---------------------------------------------------------------------------
// Handoff note section
// ---------------------------------------------------------------------------

describe('buildPrBody — handoff note', () => {
  it('includes "## Recent handoff note" section when note is present', () => {
    const result = body({ lastHandoffNote: 'Fixed the bug.' });
    expect(result).toContain('## Recent handoff note');
    expect(result).toContain('Fixed the bug.');
  });

  it('omits the handoff note section when note is null', () => {
    const result = body({ lastHandoffNote: null });
    expect(result).not.toContain('## Recent handoff note');
  });

  it('separates the note section from preceding content with a blank line', () => {
    const result = body({ recentCommits: ['a commit'], lastHandoffNote: 'My note' });
    expect(result).toContain('\n\n## Recent handoff note\n\nMy note');
  });

  it('includes multi-line handoff notes verbatim', () => {
    const note = 'Line 1\nLine 2\nLine 3';
    const result = body({ lastHandoffNote: note });
    expect(result).toContain(note);
  });
});

// ---------------------------------------------------------------------------
// Combined output
// ---------------------------------------------------------------------------

describe('buildPrBody — full output', () => {
  it('combines header, commits, and handoff note in correct order', () => {
    const result = body({
      recentCommits: ['commit A'],
      lastHandoffNote: 'important note',
    });
    const headerIdx = result.indexOf('Auto-generated by yoke on ');
    const commitIdx = result.indexOf('- commit A');
    const noteIdx = result.indexOf('## Recent handoff note');
    expect(headerIdx).toBeLessThan(commitIdx);
    expect(commitIdx).toBeLessThan(noteIdx);
  });

  it('returns a non-empty string even with no commits and no note', () => {
    const result = body();
    expect(result.length).toBeGreaterThan(20);
  });

  it('accepts workflowName in input (API conformance) without embedding it', () => {
    // RC: function takes {workflowName, recentCommits, lastHandoffNote}
    const result = buildPrBody({
      workflowName: 'test-wf',
      recentCommits: ['c1'],
      lastHandoffNote: 'note',
    });
    expect(typeof result).toBe('string');
    expect(result.length).toBeGreaterThan(0);
  });
});
